# -*- coding: utf-8 -*-
"""Opticalflowmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym98m1HJcnwYT_0EYnPwxeYyKTyUjzpX
"""

# Install required libraries for reading cloud data formats and accessing AWS public buckets
# !pip install boto3 netcdf4

import os
import sys
import torch
from torch.utils.data import ConcatDataset, DataLoader
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

# Insert parent directory to system path to enable module imports in Colab/Local scripts
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Import modular package classes
from datasets import SatelliteDataset
from models.feature_encoder import FeatureEncoder
from models.convgru import ConvGRUCell
from models.correlation import AllPairsCorrelationVolume
from models import PhysicsInformedRAFT
from losses import PhysicsInformedLoss
from evaluation import (
    plot_untrained_baseline,
    plot_inference_scaling_comparison,
    plot_netcdf_verification
)
from export import export_amv_netcdf

# --- Environment and Pipeline Re-initialization ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Running pipeline on device context: {device}")

# Define save_checkpoint function matching baseline signature and device safety
def save_checkpoint(epoch_num, model, optimizer, metrics):
    checkpoint_dir = "./model_checkpoints"
    os.makedirs(checkpoint_dir, exist_ok=True)

    # Move optimizer state to CPU before saving
    optimizer_state_on_cpu = {}
    for k, v in optimizer.state_dict().items():
        if isinstance(v, dict):
            optimizer_state_on_cpu[k] = {}
            for sub_k, sub_v in v.items():
                if isinstance(sub_v, torch.Tensor):
                    optimizer_state_on_cpu[k][sub_k] = sub_v.cpu()
                else:
                    optimizer_state_on_cpu[k][sub_k] = sub_v
        elif isinstance(v, torch.Tensor):
            optimizer_state_on_cpu[k] = v.cpu()
        else:
            optimizer_state_on_cpu[k] = v

    checkpoint_payload = {
        'epoch': epoch_num,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer_state_on_cpu,
        'final_val_loss': metrics['final_val_loss'],
        'hyperparameters': {
            'alpha': criterion.alpha,
            'beta': criterion.beta,
            'gamma': criterion.gamma
        }
    }

    checkpoint_path = os.path.join(checkpoint_dir, f"PI_RAFT_epoch_{epoch_num}.pth")
    torch.save(checkpoint_payload, checkpoint_path)

    print(f"Successfully checkpointed model state to disk container: {checkpoint_path}")
    print("Weights are secure. You can now safely close or reset your runtime environment.")


print("Initializing multi-hour GOES-16 proxy data streams...")
hours_to_fetch = [14, 15, 16, 17]

# Instantiating datasets via the new SatelliteDataset routing factory class
hourly_datasets = [
    SatelliteDataset(
        satellite='GOES16', product='ABI-L2-CMIPC', band='C09',
        year=2024, day_of_year=120, hour=h,
        sequence_length=4
    )
    for h in hours_to_fetch
]

sequence_dataset = ConcatDataset(hourly_datasets)
print(f"Total available tracking frames in sequence pool: {len(sequence_dataset)}")

sequence_loader = DataLoader(sequence_dataset, batch_size=1, shuffle=False)

# Re-instantiate architecture and load the finalized multi-constraint equation module
model = PhysicsInformedRAFT().to(device)
criterion = PhysicsInformedLoss(alpha=0.5, beta=0.1, gamma=0.01, epsilon=0.001)

print("Sequential data engine ready with split metrics tracking.")

print("Initializing unseen validation GOES-16 proxy data stream...")
val_dataset = SatelliteDataset(
    satellite='GOES16', product='ABI-L2-CMIPC', band='C09',
    year=2024, day_of_year=120, hour=18,
    sequence_length=4
)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False)

print(f"Total validation tracking frames compiled: {len(val_dataset)}")
print("Train and Validation streaming contexts successfully established.")


print("Generating Untrained Baseline Vector Field (Cell 6)...")

# Pull a single sample batch from sequence data stream
images, dem = next(iter(sequence_loader))
images = images.to(device)
dem = dem.to(device)

# Instantiate a temporary, clean model to capture the raw unoptimized state
untrained_model = PhysicsInformedRAFT().to(device)
untrained_model.eval()

# Execute a forward pass without tracking gradients
with torch.no_grad():
    flow_pred, _ = untrained_model(images, dem, iters=4)

# Render the baseline plot using the first frame from the temporal sequence
plot_untrained_baseline(images[:, 0], flow_pred, title="Cell 6: Untrained Baseline Flow Map (Random Initial State)", stride=16)

print("Cell 6 visualization baseline successfully restored.")


import torch.optim as optim

print("Initializing Adam Optimizer with Dual-Stream Train/Val Evaluation...")
optimizer = optim.AdamW(model.parameters(), lr=1e-4)

epochs = 3
step_counter = 0

for epoch in range(1, epochs + 1):
    # ==================== TRAINING PHASE ====================
    model.train()
    print(f"\n--- Starting Training Epoch {epoch}/{epochs} ---")

    for batch_idx, (images_t, dem_t) in enumerate(sequence_loader):
        images_t, dem_t = images_t.to(device), dem_t.to(device)

        optimizer.zero_grad()
        flow_pred_t, height_pred_t = model(images_t, dem_t, iters=4)
        total_loss, data_loss, physics_loss = criterion(flow_pred_t, height_pred_t, images_t)

        total_loss.backward()
        optimizer.step()

        step_counter += 1
        if step_counter % 2 == 0:
            print(
                f"Step: {step_counter:03d} | Batch: {batch_idx+1}/{len(sequence_loader)} | "
                f"TRAIN TOTAL: {total_loss.item():.4f} ---> "
                f"[Data: {data_loss.item():.4f} | Physics: {physics_loss.item():.4f}]"
            )

    # ==================== VALIDATION PHASE ====================
    model.eval()
    val_total, val_data, val_physics = 0.0, 0.0, 0.0

    print(f"\n--- Running Validation Eval for Epoch {epoch} ---")
    with torch.no_grad():
        for images_v, dem_v in val_loader:
            images_v, dem_v = images_v.to(device), dem_v.to(device)

            flow_pred_v, height_pred_v = model(images_v, dem_v, iters=4)
            v_total, v_data, v_physics = criterion(flow_pred_v, height_pred_v, images_v)

            val_total += v_total.item()
            val_data += v_data.item()
            val_physics += v_physics.item()

    # Calculate dataset-wide average scores
    num_val_batches = len(val_loader)
    avg_val_total_loss = val_total / num_val_batches
    print(f"====== VAL METRICS EPOCH {epoch} ======")
    print(f"Avg VAL Total Loss:     {avg_val_total_loss:.4f}")
    print(f"Avg VAL Data Domain:    {val_data / num_val_batches:.4f}")
    print(f"Avg VAL Physics Domain: {val_physics / num_val_batches:.4f}")
    print("======================================\n")

    # Call the checkpointing function
    val_metrics = {'final_val_loss': avg_val_total_loss}
    save_checkpoint(epoch, model, optimizer, val_metrics)


print("Multi-epoch training and verification pipeline execution complete!")
print("Checkpointing handled via function call in training loop.")


print("Executing Milestone 4: Inference Iteration Scaling Analysis...")

# Grab a fresh test sequence frame from the validation datastream
model.eval()
images_val, dem_val = next(iter(val_loader))
images_val = images_val.to(device)
dem_val = dem_val.to(device)

# Compute inference at standard training depth (iters=4)
with torch.no_grad():
    flow_low_res, _ = model(images_val, dem_val, iters=4)

# Compute inference at scaled production depth (iters=12)
with torch.no_grad():
    flow_high_res, height_pred_val = model(images_val, dem_val, iters=12)

# Plot scaling comparison using the first frame from the sequence as reference
plot_inference_scaling_comparison(
    images_val[:, 0], flow_low_res, flow_high_res,
    standard_iters=4, production_iters=12,
    scale_factor=0.1, stride=16
)

print("Iteration scaling visualization rendered successfully.")


print("Initializing Milestone 6: Meteorological NetCDF4 Export Engine...")

# Strip batch dimensions and shift PyTorch tensors back into CPU NumPy matrices
u_array = flow_high_res.squeeze(0)[0].cpu().numpy()
v_array = flow_high_res.squeeze(0)[1].cpu().numpy()
p_array = height_pred_val.squeeze(0)[0].cpu().numpy()

# Set up local output directory
output_dir = "./outputs/meteorological_outputs"
os.makedirs(output_dir, exist_ok=True)
nc_filepath = os.path.join(output_dir, "INSAT_3DS_AMV_Derived_Wind.nc")

# Call modular export package function (fixes Windows-specific path issues)
export_amv_netcdf(u_array, v_array, p_array, nc_filepath)

# Load exported NetCDF dataset directly from disk to verify
ds = xr.open_dataset(nc_filepath)
print(ds)

# Verify netCDF file using modular evaluation plotting function
plot_netcdf_verification(nc_filepath, title="NetCDF4 Export Verification (Institutional Spec)")